version: '3'
services:
  openvpn:
    cap_add:
    - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    networks:
      app_net:
        ipv4_address: 172.22.0.2
    ports:
    - "1194:1194/udp"
    restart: always
    volumes:
    - ./openvpn-data/conf:/etc/openvpn
  udp2raw_server:
    cap_add:
    - NET_ADMIN
    image: wangyucn/udp2raw-tunnel
    container_name: udp2raw_server
    entrypoint: udp2raw_dynamic -s -l0.0.0.0:65535 -r 172.22.0.2:1194  -a -k "passwd" --raw-mode faketcp
    networks:
      app_net:
        ipv4_address: 172.22.0.3
    ports:
    - "65535:65535/udp"
    - "65535:65535/tcp"
    restart: always
  udp2raw_client:
    cap_add:
    - NET_ADMIN
    image: wangyucn/udp2raw-tunnel
    container_name: udp2raw_client
    entrypoint: udp2raw_dynamic -c -l0.0.0.0:65534  -r172.22.0.3:65535 -a -k "passwd" --raw-mode faketcp
    networks:
      app_net:
        ipv4_address: 172.22.0.4
    ports:
    - "65534:65534/udp"
    restart: always
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24 

