version: '2'
services:
  udp2raw:
    cap_add:
    - NET_ADMIN
    image: turingking/udp2raw
    container_name: udp2raw
    entrypoint: -c -l0.0.0.0:4096  -rturingking.com:65534 -k "passwd" --raw-mode faketcp   --cipher-mode xor  -a
    ports:
    restart: always

  tinyvpn:
    cap_add:
    - NET_ADMIN
    image: turingking/tinyvpn
    container_name: tinyvpn
    entrypoint: -c -rudp2raw:4096 -f20:10 -k "passwd" --sub-net 10.22.22.0
    ports:
    - "65534:65534"
    restart: always

